import type {
  DevotionalBlockId,
  DevotionalId,
} from "../../domain/devotionals/devotional";
import type { DevotionalContentPackage } from "./devotionalContentPackage";

export const devotionalJesusCordeiroDraft: DevotionalContentPackage = {
  id: "devotional-track05-jesus-cordeiro-draft" as DevotionalId,
  contentType: "DEVOTIONAL",
  format: "OPEN_LETTER",
  placement: "TRACK_05",
  title: "Jesus, o Cordeiro de Deus",
  subtitle: "Uma mensagem de esperança, salvação e vida eterna em Cristo.",
  summary: null,
  audience: null,
  author: {
    canonicalName: "Decleones Andrade",
    publicProfile: {
      displayName: "Decleones Andrade",
      role: "Músico",
      formation: null,
      cityState: "Rondonópolis/MT",
    },
    publicDisplayAuthorization: "AUTHORIZED",
  },
  heroImage: "assets/devotionals/heroes/devotional-jesus-cordeiro.png",
  blocks: [
    {
      id: "cordeiro-b01" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Escrevo esta carta com o coração cheio de temor, amor e esperança. Escrevo para todos que estão cansados, feridos, confusos, sobrecarregados ou distantes de Deus; para quem já sentiu o peso do pecado, o medo da morte, a dor da perda, o vazio da alma e a saudade de algo maior, eterno, que este mundo não consegue oferecer.",
    },
    {
      id: "cordeiro-b02" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Mas também escrevo para quem ama Jesus, para quem já foi alcançado pela graça, para quem foi lavado pelo sangue do Cordeiro e sabe que nossa esperança não termina aqui. O melhor de Deus ainda está por vir: viver para sempre com Cristo, no Reino eterno que Ele preparou para os seus.",
    },
    {
      id: "cordeiro-b03" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Esta carta é sobre Jesus: o Cordeiro prometido, ferido, morto, ressurreto, digno, que reina e que voltará para buscar os que são seus. Antes de falarmos da glória eterna, precisamos lembrar que tudo começou com o amor de Deus por um povo que não podia se salvar sozinho.",
    },
    {
      id: "cordeiro-b04" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "EXO",
        startChapter: 12,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b05" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Em Êxodo 12, o povo de Israel estava preso no Egito, sofrido, escravizado e sem força para se libertar por conta própria. Deus ordena que cada família tome um cordeiro sem defeito, o sacrifique e passe o sangue nas portas. Onde houvesse o sangue, haveria livramento. O material apresenta esse cordeiro da Páscoa como sinal que apontava para Jesus.",
    },
    {
      id: "cordeiro-b06" as DevotionalBlockId,
      kind: "HEADING",
      level: 2,
      text: "O verdadeiro Cordeiro",
    },
    {
      id: "cordeiro-b07" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "ISA",
        startChapter: 6,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b08" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Ao lembrar Isaías 6, a carta destaca a santidade de Deus e a consciência humana de impureza diante dessa santidade. A reflexão insiste que ninguém entende a graça enquanto não encara a santidade e a necessidade de misericórdia.",
    },
    {
      id: "cordeiro-b09" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "ISA",
        startChapter: 53,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b10" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Em Isaías 53, a carta identifica o Servo sofredor: desprezado, rejeitado, ferido e moído por causa dos pecados, levando dores e sendo conduzido como cordeiro ao matadouro. O texto autoral aplica essa imagem a Jesus, afirmando que Ele foi à cruz por amor e obediência.",
    },
    {
      id: "cordeiro-b11" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "JHN",
        startChapter: 1,
        startVerse: 29,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b12" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Quando João Batista vê Jesus se aproximando, em João 1:29, a carta reconhece nele o Cordeiro de Deus que tira o pecado do mundo e reúne nessa declaração o sentido que o autor enxerga em toda a trajetória bíblica apresentada.",
    },
    {
      id: "cordeiro-b13" as DevotionalBlockId,
      kind: "LIST",
      style: "BULLET",
      items: [
        "Jesus é o Cordeiro pascal e o Servo sofredor.",
        "Jesus é o Santo que se aproximou dos pecadores.",
        "Jesus é o sangue na porta da alma.",
        "Jesus é a ponte entre o Deus santo e o homem caído.",
      ],
    },
    {
      id: "cordeiro-b14" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Na cruz, Jesus carregou aquilo que era nosso: culpa, vergonha, condenação e dor. A carta afirma que ali a justiça de Deus e o amor de Deus se encontraram, o pecado foi julgado, a graça foi revelada, a dívida foi cravada e o preço foi pago, o véu se rasgou e a porta da salvação foi aberta.",
    },
    {
      id: "cordeiro-b15" as DevotionalBlockId,
      kind: "HEADING",
      level: 2,
      text: "O Cordeiro que foi morto está vivo",
    },
    {
      id: "cordeiro-b16" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "A história do Cordeiro não termina no sofrimento e no túmulo. A carta proclama que Jesus morreu e ressuscitou, venceu a morte, o pecado e o inferno e ressuscitou com poder e autoridade.",
    },
    {
      id: "cordeiro-b17" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "PSA",
        startChapter: 24,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b18" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Ao recorrer ao Salmo 24, a carta identifica Jesus como o Rei da Glória: o Cordeiro que venceu, o Leão da tribo de Judá, aquele que foi ferido e agora vive, foi humilhado e agora é exaltado.",
    },
    {
      id: "cordeiro-b19" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "REV",
        startChapter: 5,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b20" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Em Apocalipse 5, João vê o livro selado e chora diante da ausência de alguém digno de abri-lo. A carta interpreta esse choro como expressão de uma história aparentemente sem saída, até que surge a notícia de que o Leão da tribo de Judá venceu. João ouve falar de um Leão, mas vê um Cordeiro.",
    },
    {
      id: "cordeiro-b21" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "O Leão venceu como Cordeiro. O Cordeiro aparece como tendo sido morto, mas está em pé diante do trono. Quando toma o livro, o céu se move em adoração. O centro enfatizado pela carta é que fomos comprados para Deus pelo sangue de Jesus, chamados para uma nova vida e para uma esperança que ultrapassa este mundo.",
    },
    {
      id: "cordeiro-b22" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "REV",
        startChapter: 7,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b23" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Apocalipse 7 é apresentado como visão de uma multidão de todas as nações, tribos, povos e línguas diante do trono e do Cordeiro. A carta testemunha que o sangue de Jesus limpa, purifica, transforma e dá nova identidade marcada por graça, perdão e esperança.",
    },
    {
      id: "cordeiro-b24" as DevotionalBlockId,
      kind: "BIBLE_REFERENCE",
      reference: {
        bookId: "REV",
        startChapter: 21,
        startVerse: null,
        endChapter: null,
        endVerse: null,
      },
    },
    {
      id: "cordeiro-b25" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Ao olhar para Apocalipse 21, a carta aponta para novo céu e nova terra, a Santa Cidade e Deus habitando com seu povo. Não haverá mais morte, pranto, clamor ou dor. O autor apresenta essa esperança como promessa de Deus e como destino dos salvos em Cristo.",
    },
    {
      id: "cordeiro-b26" as DevotionalBlockId,
      kind: "LIST",
      style: "BULLET",
      items: [
        "Toda dor vai acabar.",
        "Todo choro vai cessar.",
        "Toda ferida será curada.",
        "Toda injustiça será julgada.",
        "Toda saudade será vencida.",
        "Toda morte será destruída.",
        "O pecado não terá mais lugar.",
        "A tristeza não terá mais voz.",
        "A separação não existirá mais.",
      ],
    },
    {
      id: "cordeiro-b27" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Por isso, o autor escreve com o desejo de que ninguém trate Jesus como algo distante, despreze o sangue do Cordeiro ou viva como se não houvesse eternidade. Ele deseja que todos conheçam salvação, perdão, esperança e vida nova em Cristo e experimentem a alegria de pertencer a Jesus.",
    },
    {
      id: "cordeiro-b28" as DevotionalBlockId,
      kind: "LIST",
      style: "BULLET",
      items: [
        "Não tente carregar sozinho aquilo que só Ele pode levar.",
        "Não tente vencer o pecado apenas com força humana.",
        "Não tente comprar o que só o sangue de Cristo pode pagar.",
        "Não endureça seu coração.",
        "Não deixe para depois.",
        "Não pense que está longe demais.",
        "Não pense que Deus não pode restaurar sua vida.",
      ],
    },
    {
      id: "cordeiro-b29" as DevotionalBlockId,
      kind: "ACTION",
      text: "Arrependa-se. Volte-se para Deus. Creia em Jesus Cristo. Entregue sua vida ao Cordeiro. Viva como quem pertence ao céu, caminhe como quem foi comprado por Deus, adore como quem foi alcançado pela misericórdia e espere como quem sabe que o melhor ainda está por vir.",
    },
    {
      id: "cordeiro-b30" as DevotionalBlockId,
      kind: "CALLOUT",
      role: "AUTHOR_EMPHASIS",
      text: "Digno é o Cordeiro. Digno é o Cordeiro que foi morto. Digno é o Cordeiro que ressuscitou. Digno é o Cordeiro que comprou para Deus homens de toda tribo, língua, povo e nação. Ao que está assentado no trono e ao Cordeiro sejam o louvor, a honra, a glória e o domínio pelos séculos dos séculos.",
    },
    {
      id: "cordeiro-b31" as DevotionalBlockId,
      kind: "PARAGRAPH",
      text: "Que Deus abençoe sua vida de uma maneira diferente a partir de hoje, recompensando seus esforços para salvação e ajudando seu caminhar diário. Atenciosamente, de seu irmão em Cristo Jesus: Decleones Andrade.",
    },
  ],
  bibleReferences: [
    {
      bookId: "EXO",
      startChapter: 12,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "ISA",
      startChapter: 6,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "ISA",
      startChapter: 53,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "JHN",
      startChapter: 1,
      startVerse: 29,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "PSA",
      startChapter: 24,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "REV",
      startChapter: 5,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "REV",
      startChapter: 7,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
    {
      bookId: "REV",
      startChapter: 21,
      startVerse: null,
      endChapter: null,
      endVerse: null,
    },
  ],
  reflectionPrompt: null,
  governance: {
    editorialStatus: "PUBLISHED",
    contentReview: "APPROVED",
    theologicalReview: "APPROVED",
    publicDisplayAuthorization: "AUTHORIZED",
    publicationAuthorization: "AUTHORIZED",
  },
  source: {
    sourceKind: "AUTHORIAL",
    originalTitle: "Jesus, o Cordeiro de Deus",
    receivedAs: "carta aberta",
    sourceFileName: "Carta Aberta _Jesus o Cordeiro de Deus.pdf",
    sourceSha256: "3889CB8EAF991A5DC9F7DDC0D501FC21801CEE129A6A8441D11C368D20E668A4",
    curatorNotes: [
      "O documento-fonte se apresenta explicitamente como Carta Aberta e é preservado como OPEN_LETTER, sem conversão para Study.",
      "A assinatura DECLEONES ANDRADE no próprio PDF sustenta a identidade interna do autor; a autorização de exibição pública no app foi confirmada pelo responsável do projeto.",
      "A estrutura deste conteúdo agrupa o fluxo da carta em blocos e normaliza apenas quebras de linha e artefatos evidentes da extração PDF; as afirmações autorais e teológicas foram submetidas à revisão final de ativação, preservando-se como voz autoral quando interpretativas.",
      "As referências estruturadas foram limitadas às passagens explicitamente identificáveis no material-fonte.",
      "A aprovação editorial e teológica e a autorização de publicação foram confirmadas pelo responsável do projeto na etapa controlada de ativação.",
    ],
  },
};
