const ALM1911_HISTORICAL_HEADING_ALIASES: Readonly<
  Record<string, readonly string[]>
> = Object.freeze({
  GEN: ["GENESIS"],
  EXO: ["EXODO"],
  LEV: ["LEVITICO"],
  NUM: ["NUMEROS"],
  DEU: ["DEUTERONOMIO"],
  JOS: ["JOSUE"],
  JDG: ["JUIZES"],
  RUT: ["RUTH"],
  "1SA": ["SAMUEL"],
  "2SA": ["SAMUEL"],
  "1KI": ["REIS"],
  "2KI": ["REIS"],
  "1CH": ["CHRONICAS"],
  "2CH": ["CHRONICAS"],
  EZR: ["ESDRAS"],
  NEH: ["NEHEMIAS"],
  EST: ["ESTHER"],
  JOB: ["JOB"],
  PSA: ["PSALMOS"],
  PRO: ["PROVERBIOS"],
  ECC: ["ECCLESIASTES"],
  SNG: ["CANTARES", "CANTICO", "CANTICOS"],
  ISA: ["ISAIAS"],
  JER: ["JEREMIAS"],
  LAM: ["LAMENTACOES"],
  EZK: ["EZEQUIEL"],
  DAN: ["DANIEL"],
  HOS: ["OSEAS"],
  JOL: ["JOEL"],
  AMO: ["AMOS"],
  OBA: ["OBADIAS"],
  JON: ["JONAS"],
  MIC: ["MICHEAS", "MIQUEAS"],
  NAM: ["NAHUM"],
  HAB: ["HABACUC"],
  ZEP: ["SOFONIAS", "SOPHONIAS"],
  HAG: ["AGGEO", "AGEO"],
  ZEC: ["ZACHARIAS"],
  MAL: ["MALACHIAS"],
  MAT: ["MATTHEUS"],
  MRK: ["MARCOS"],
  LUK: ["LUCAS"],
  JHN: ["JOAO"],
  ACT: ["ACTOS"],
  ROM: ["ROMANOS"],
  "1CO": ["CORINTHIOS"],
  "2CO": ["CORINTHIOS"],
  GAL: ["GALATAS"],
  EPH: ["EPHESIOS"],
  PHP: ["PHILIPPENSES"],
  COL: ["COLOSSENSES"],
  "1TH": ["THESSALONICENSES"],
  "2TH": ["THESSALONICENSES"],
  "1TI": ["TIMOTHEO"],
  "2TI": ["TIMOTHEO"],
  TIT: ["TITO"],
  PHM: ["PHILEMON"],
  HEB: ["HEBREOS"],
  JAS: ["THIAGO"],
  "1PE": ["PEDRO"],
  "2PE": ["PEDRO"],
  "1JN": ["JOAO"],
  "2JN": ["JOAO"],
  "3JN": ["JOAO"],
  JUD: ["JUDAS"],
  REV: ["APOCALYPSE"],
});

export const ALM1911_HISTORICAL_HEADING_ALIAS_BOOK_COUNT =
  Object.keys(ALM1911_HISTORICAL_HEADING_ALIASES).length;

export function getAlmeida1911HistoricalHeadingAliases(
  bookId: string,
): readonly string[] {
  return ALM1911_HISTORICAL_HEADING_ALIASES[bookId] ?? [];
}
