import type { ImageSourcePropType } from "react-native";

import type { BibleBookId } from "../../domain/bible/bibleReference";

/**
 * Static artwork contract for all 66 canonical Bible books.
 * Asset references remain literal so Metro can bundle every local image.
 */
export const BIBLE_BOOK_ART = {
  "GEN": require("../../../assets/bible/books/genesis.jpg"),
  "EXO": require("../../../assets/bible/books/exodo.jpg"),
  "LEV": require("../../../assets/bible/books/levitico.jpg"),
  "NUM": require("../../../assets/bible/books/numeros.jpg"),
  "DEU": require("../../../assets/bible/books/deuteronomio.jpg"),
  "JOS": require("../../../assets/bible/books/josue.jpg"),
  "JDG": require("../../../assets/bible/books/juizes.jpg"),
  "RUT": require("../../../assets/bible/books/rute.jpg"),
  "1SA": require("../../../assets/bible/books/1_samuel.jpg"),
  "2SA": require("../../../assets/bible/books/2_samuel.jpg"),
  "1KI": require("../../../assets/bible/books/1_reis.jpg"),
  "2KI": require("../../../assets/bible/books/2_reis.jpg"),
  "1CH": require("../../../assets/bible/books/1_cronicas.jpg"),
  "2CH": require("../../../assets/bible/books/2_cronicas.jpg"),
  "EZR": require("../../../assets/bible/books/esdras.jpg"),
  "NEH": require("../../../assets/bible/books/neemias.jpg"),
  "EST": require("../../../assets/bible/books/ester.jpg"),
  "JOB": require("../../../assets/bible/books/jo.jpg"),
  "PSA": require("../../../assets/bible/books/salmos.jpg"),
  "PRO": require("../../../assets/bible/books/proverbios.jpg"),
  "ECC": require("../../../assets/bible/books/eclesiastes.jpg"),
  "SNG": require("../../../assets/bible/books/canticos.jpg"),
  "ISA": require("../../../assets/bible/books/isaias.jpg"),
  "JER": require("../../../assets/bible/books/jeremias.jpg"),
  "LAM": require("../../../assets/bible/books/lamentacoes.jpg"),
  "EZK": require("../../../assets/bible/books/ezequiel.jpg"),
  "DAN": require("../../../assets/bible/books/daniel.jpg"),
  "HOS": require("../../../assets/bible/books/oseias.jpg"),
  "JOL": require("../../../assets/bible/books/joel.jpg"),
  "AMO": require("../../../assets/bible/books/amos.jpg"),
  "OBA": require("../../../assets/bible/books/obadias.jpg"),
  "JON": require("../../../assets/bible/books/jonas.jpg"),
  "MIC": require("../../../assets/bible/books/miqueias.jpg"),
  "NAM": require("../../../assets/bible/books/naum.jpg"),
  "HAB": require("../../../assets/bible/books/habacuque.jpg"),
  "ZEP": require("../../../assets/bible/books/sofonias.jpg"),
  "HAG": require("../../../assets/bible/books/ageu.jpg"),
  "ZEC": require("../../../assets/bible/books/zacarias.jpg"),
  "MAL": require("../../../assets/bible/books/malaquias.jpg"),
  "MAT": require("../../../assets/bible/books/mateus.jpg"),
  "MRK": require("../../../assets/bible/books/marcos.jpg"),
  "LUK": require("../../../assets/bible/books/lucas.jpg"),
  "JHN": require("../../../assets/bible/books/joao.jpg"),
  "ACT": require("../../../assets/bible/books/atos.jpg"),
  "ROM": require("../../../assets/bible/books/romanos.jpg"),
  "1CO": require("../../../assets/bible/books/1_corintios.jpg"),
  "2CO": require("../../../assets/bible/books/2_corintios.jpg"),
  "GAL": require("../../../assets/bible/books/galatas.jpg"),
  "EPH": require("../../../assets/bible/books/efesios.jpg"),
  "PHP": require("../../../assets/bible/books/filipenses.jpg"),
  "COL": require("../../../assets/bible/books/colossenses.jpg"),
  "1TH": require("../../../assets/bible/books/1_tessalonicenses.jpg"),
  "2TH": require("../../../assets/bible/books/2_tessalonicenses.jpg"),
  "1TI": require("../../../assets/bible/books/1_timoteo.jpg"),
  "2TI": require("../../../assets/bible/books/2_timoteo.jpg"),
  "TIT": require("../../../assets/bible/books/tito.jpg"),
  "PHM": require("../../../assets/bible/books/filemon.jpg"),
  "HEB": require("../../../assets/bible/books/hebreus.jpg"),
  "JAS": require("../../../assets/bible/books/tiago.jpg"),
  "1PE": require("../../../assets/bible/books/1_pedro.jpg"),
  "2PE": require("../../../assets/bible/books/2_pedro.jpg"),
  "1JN": require("../../../assets/bible/books/1_joao.jpg"),
  "2JN": require("../../../assets/bible/books/2_joao.jpg"),
  "3JN": require("../../../assets/bible/books/3_joao.jpg"),
  "JUD": require("../../../assets/bible/books/judas.jpg"),
  "REV": require("../../../assets/bible/books/apocalipse.jpg"),
} as const satisfies Readonly<
  Record<BibleBookId, ImageSourcePropType>
>;